title:            By vliux.me
tagline:
description:      
canonical: http://vliux.me
production_url : http://vliux.me
url: http://vliux.me

# Owner/author information
owner:
  name:           vliux
  avatar:         avatar.png
  email:          swordmanliuxin@gmail.com
  500px:          xinliu4
  500pxc:         vliux
  github:         vliux
  instagram:      vliux
  disqus:         vliuxonsoftware
  location:       "Hangzhou, China"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: Photography
    url: /gallery
  - title: Tech
    url: /blog
  #- title: 500px
  #  url: https://500px.com/xinliu4
  #  external: true
  #- title: 500px中国
  #  url: https://500px.me/vliux
  #  external: true
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    sass_dir: _sass
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]

gems: [jekyll-paginate-v2]

# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  enabled: true
  debug: true
  per_page: 7

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  #title: ':title (page :num)'
  title: ':title'
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true


